package com.suilearn.api.model;

public enum TaskKind {
    MATERIAL_IMPORT,
    MATERIAL_REPROCESS,
    EMBEDDING,
    QUESTION_GENERATION,
    KNOWLEDGE_POINT_EXTRACTION,
    EXPLANATION_GENERATION,
    REVIEW_SUGGESTION_GENERATION
}
